### ISSUE TITLE
JOSS review - demo jupyter notebook

### ISSUE THREAD

**Issue by KatyBrown** [Clinical-Genomics-Umea/fraggler#15]
Issue raised as part of the JOSS review process to address the "Functionality"  check https://github.com/openjournals/joss-reviews/issues/6869

In the demo Jupyter notebook, some of the commands do not work with the version of the code currently on pip - I think the final three functions in `fraggler.py` - `fit_ladder`, `find_peaks` and `fit_area` must be elsewhere in that version as there are ImportErrors for these functions.

I therefore cloned the git repo directly and imported fraggler.fraggler from the cloned folder but this led to different errors - I would guess that the `fraggler.FsaFile` function has some different parameters in the current version of the code on GitHub than in the tutorial, as it expected `sample_channel`, `min_distance_between_peaks` and `min_size_standard_height` to be specified but they are not in the notebook, and it didn't recognise `trace_channel`.

I didn't progress past that point but it seems like the tutorial for the Python version of the code needs updating to be usable.

**Comment by kdm9** [comment]
Additionally, the link to `tutorial.ipynb` in the paper is broken (points to root of repo, not to the demo dir).

**Comment by willros** [comment]
Hi @KatyBrown and @kdm9!

I have updated the version of fraggler on pypi. The tutorial works for me when I pip install the latest version of fraggler. 
Try it out and let me know if it still does not work.

William

**Comment by KatyBrown** [comment]
Thank you, the tutorial works nicely now.
