### ISSUE TITLE
JOSS review - API documentation

### ISSUE THREAD

**Issue by KatyBrown** [Clinical-Genomics-Umea/fraggler#16]
Issue raised as part of the JOSS review process to address the "Functionality Documentation" check https://github.com/openjournals/joss-reviews/issues/6869

The link to the API documentation in the README.md leads to a page which I think has missing information - https://clinical-genomics-umea.github.io/fraggler/fraggler.html - here I just see the below:
![image](https://github.com/Clinical-Genomics-Umea/fraggler/assets/8896865/6d349a0a-6251-4edf-a859-cc1d27f36325)

The "fraggler" submodule link leads to the detailed code documentation describing the functions - but there is no overview of how to use the API version of the tool.

**Comment by willros** [comment]
Hi @KatyBrown!

The API of Fraggler is best demonstrated in the `tutorial.ipynb`. This notebook documents everything needed to use Fraggler in a Python environment.

The link to the documentation provides a comprehensive overview of the source code. I have tried to document and describe the code thoroughly, making it easy to understand the logic and flow.

Hope this helps!

William

**Comment by KatyBrown** [comment]
I see,  I was expecting that the link above was the main documentation of the API.
